### ISSUE TITLE
Start timer for a bucket only after the first set() is called?

### ISSUE THREAD

**Issue by blai** [analog-nico/two-buckets-memcache#1]
First of, thanks for sharing this great component!

I haven't look into your code yet, and is commenting based on your documentation, so you may be doing this already. It seems like we can optimize this a little further by only starting a timer for a bucket after the first `set()` is called upon it. I think the advantage is two folds:
1. Cut down the overhead when some bucket is never used, and you end up busy replacing an empty bucket with another.
2. Since the timer is only starting when the first item is put into it, you are essentially normalizing the expiration time for all items toward 20 seconds (per your example), so they are a little more consistent.

**Comment by analog-nico** [comment]
Hi @blai very good idea! I'll add that right away.

**Comment by analog-nico** [comment]
My "right away" took me nearly 6 months. :D But it is done now! :)
